const vm = require('node:vm');
const fs = require('node:fs');
const assert = require('node:assert/strict');
let rows = [['Family', 'holder@example.com', 2, 'ABCDEF1234567890ABCDEF1234', 'Sí']];
const ctx = vm.createContext({ SpreadsheetApp: {openById: () => ({getSheetByName: () => ({getLastRow: () => rows.length + 1, getRange: () => ({getValues: () => rows})})})}, RSVP_SPREADSHEET_ID: 'test' });
vm.runInContext(fs.readFileSync(__dirname + '/Invitations.gs', 'utf8'), ctx);
assert.equal(ctx.findInvitation(' abcdef1234567890abcdef1234 ').maxGuests, 2);
rows[0][2] = 1;
assert.equal(ctx.findInvitation('ABCDEF1234567890ABCDEF1234').maxGuests, 1);
rows[0][4] = 'No'; assert.throws(() => ctx.findInvitation('ABCDEF1234567890ABCDEF1234'));
rows[0][4] = 'Sí'; rows.push([...rows[0]]); assert.throws(() => ctx.findInvitation('ABCDEF1234567890ABCDEF1234')); rows.pop();
assert.throws(() => ctx.findInvitation('wrong-code'));
const person = {fullName:'Holder', email:'holder@example.com', attendance:'yes', dietaryPreference:'none', allergiesNote:'None'};
const data = {fullName:'Holder',email:'holder@example.com', attendance:'yes',plusOneCount:1,guests:[person]};
assert.equal(ctx.validatePeople(data, {email:'holder@example.com',maxGuests:1}).length, 1);
assert.throws(() => ctx.validatePeople({...data,guests:[person,person]}, {email:'holder@example.com',maxGuests:1}));
assert.throws(() => ctx.validatePeople({...data,email:'other@example.com'}, {email:'holder@example.com',maxGuests:1}));
assert.throws(() => ctx.validatePeople({...data,plusOneCount:2}, {email:'holder@example.com',maxGuests:2}));
const extra = {...person,fullName:'Guest',email:'',dietaryPreference:'vegan',allergiesNote:'Nuts'};
const people = ctx.validatePeople({...data,plusOneCount:2,guests:[person,extra]}, {email:'holder@example.com',maxGuests:2});
assert.equal(people[1].allergiesNote, 'Nuts'); assert.equal(people[0].allergiesNote, 'None');
assert.equal(ctx.validatePeople({...data,attendance:'no',plusOneCount:0,guests:[{...person,attendance:'no'}]}, {email:'holder@example.com',maxGuests:1})[0].allergiesNote, '');
console.log('Invitation validation passed: live limits, inactive/duplicate/invalid codes, email binding, tampered count, individual allergies, declined guests.');
